### ISSUE TITLE
Autocomplete MIA

### ISSUE THREAD

**Issue by Road-block** [shirsig/postal#14]
Autocomplete seems to be gone as of https://github.com/shirsig/postal/commit/e1929a791ade1b7d10569d39657260c65e60d6b6  
Might be an issue earlier but my last version was before the latest refactoring.  
_Also off-topic to this ticket, postal doesn't upgrade gracefully on overwrites (the capitalization change to the addon name / toc)_  
It needs a deletion of the addon folder (at least on windows overwriting folders ignores capitalization so you end up with **P**ostal and that's a slew of errors in game)

**Comment by shirsig** [comment]
Yeah, you should download a fresh zip for the capitalization issue. Autocompletion still works fine for me. Are you talking about autocompletion of alts only? The savedvariable they're stored in changed so they would have been wiped, so you would need to log onto them again to reenable them for autocompletion.

**Comment by Road-block** [comment]
It's not the fresh zip that's the issue.  
When you overwrite folders on windows machines with a folder that has just a capitalization change that change is ignored.  
i.e. Overwrite `Postal` folder with a `postal` folder windows explorer won't overwrite the case of the folder or the files it will remain as capital P.  
About the autocompletion part I'll get back to you shortly, I noticed the same capitalization issue with the savedvariables files (Postal.lua instead of postal.lua) and was checking if that has something to do with it, but if sv is reset that's probably the real reason (i.e. user error 😛 )

**Comment by shirsig** [comment]
I mean you should delete the folder download a fresh zip, remove the -master and put it in your addon folder.

**Comment by Road-block** [comment]
I get you, I obviously already did that before I made the ticket 😃   
I'm just saying it needs to be clear for users that a new zip and overwrite is not enough.

**Comment by shirsig** [comment]
I suppose, but first of all I think it should always be done this way anyway as there can be other issues too and secondly, I simply have no way of communicating that well enough to reach all users. In fact, probably so few that it's not worth it. I mean for example I've often made a post in the nost/kronos/elysium forums about the new update of some addon needing you to delete all savedvariables or something. Still ended up getting numerous comments/pms/issues about it anyway.
