### ISSUE TITLE
adding items via right-click

### ISSUE THREAD

**Issue by brolernus** [shirsig/postal#15]
downloaded newest version today, cant seem to get it to work

**Comment by shirsig** [comment]
always update by deleting the folder and replacing it with a new one

**Comment by brolernus** [comment]
10/10 feedback man
your shit is still fucked up, im not that retarded
adding items via right-click doesnt work (deleted prior savedvars etc.)

**Comment by shirsig** [comment]
You really deleted the old folder?

**Comment by brolernus** [comment]
deleted the old Interface/AddOns/Postal aswell as every single saved var. WTF/Account/Accountname/SavedVariables/... aswell as for every single /Server/Charactername/SavedVariables/... .lua and .lua.bak
so basicly i did a full sweep before downloading your latest version.

**Comment by shirsig** [comment]
works just fine for mee. even made it work directrly from the inbox tab. Try deactivating other addons for conflicts?

**Comment by brolernus** [comment]
downloaded an older version from 9th February which works correctly with right-clicking items out of the bag to add them to the mail.

**Comment by brolernus** [comment]
problems seems to be caused by lazypig (this version: https://github.com/satan666/_LP).
But like i said your older versions worked fine with it, thats why i thought the problem lies in one of those updates you made recently

**Comment by shirsig** [comment]
can't see anything between those commits. can't you disable this feature in lazypig?

**Comment by brolernus** [comment]
works now if you disable lazypigs "improved right click". I'm still curious as to what may be the cause of that. alot of players are using that exact version of lazypig so you might want to add a notation somewhere that it can cause issues now.

**Comment by shirsig** [comment]
Yeah I'll try and find out

**Comment by shirsig** [comment]
Well, I've looked at it and basically it just hooks the same function (usecontaineritem), at a later time, and on right click does its own stuff and ignores the original function (including postal's addition). There is no real solution for those kind of conflicts besides not using addons that hook the same functions. I could make it hook later which would overwrite lazypig in this case but might in turn cause conflicts with other addons ...

**Comment by Cephel** [comment]
Since lazypig does the same thing for mail (right click to attach item), why not just detect the presence of Lazypig and then just not hook the function from this side, but instead try to redirect the container target, basically reusing their code for your purpose.

Lazypig does more than just mail, so not using improved right click isn't an option, whereas adding compatibility from this side seems reasonably easy.

**Comment by shirsig** [comment]
But hardcoding other addons' names is the worst way imaginable to make them compatible. Customizing the individual hooking times would be almost as bad. I've now delayed all hooks to the player login event which should solve this issue but may cause others ...
