### ISSUE TITLE
Cannot send multiple outgoing mails?

### ISSUE THREAD

**Issue by Havenloft** [shirsig/postal#16]
I'm trying to send 2 recipes to my brother.  I send him stuff all of the time and love Postal for it's ability to send everything at once.  Unfortunately, it stopped working after I updated it this morning.  It will not even let me send the items 1 at a time.  I now get these errors:

Error:  Attempt to index global 'postalMailButton' (a nil value)
File: Interface\AddOns\Postal\Postal.lua
Line: 518
Count: 7

Error:  Attempt to index global 'postalMailButton' (a nil value)
File: Interface\AddOns\Postal\Postal.lua
Line: 518
Count: 11

**Comment by shirsig** [comment]
https://github.com/shirsig/postal/issues/15
