### ISSUE TITLE
Ability to not delete mails with text in them

### ISSUE THREAD

**Issue by Cephel** [shirsig/postal#17]
I don't like that the auto open all mail function deletes mails ,even if someone sent you a proper actual mail. By the time you realize what's happening, the addon might have already deleted the mail.

**Comment by shirsig** [comment]
but the ratio of gold spam to regular mail is about 100000/1

**Comment by Cephel** [comment]
Could be an option somewhere

**Comment by shirsig** [comment]
Meh, just use the right click opening for more precision.
