### ISSUE TITLE
Addon completely broken

### ISSUE THREAD

**Issue by Cephel** [shirsig/postal#18]
I think this happened between 5614a8fad5d7f118f49c3d74149f3ef4b5cedc4f and e1929a791ade1b7d10569d39657260c65e60d6b6

**Comment by Road-block** [comment]
You might have been caught out by https://github.com/shirsig/postal/issues/14

**Comment by shirsig** [comment]
yes

**Comment by Cephel** [comment]
Depends, I update my addon via ```git submodule```, I'll check if this is also the case here
