### ISSUE TITLE
nothing happend

### ISSUE THREAD

**Issue by Mixuspidelix** [shirsig/postal#19]
with ne newest version, nothing happend when i will open my mails - no error´s nothing :s 

i delete all my lua.files in the Addon-Folder + in the Wtf-Folder...but yeah - it dosn´t go :(

Mixus

Ps: i use a german-client

**Comment by shirsig** [comment]
#15 ?

**Comment by Mixuspidelix** [comment]
Hey shirsig - i don´t use lazypig :s

**Comment by shirsig** [comment]
Dunno but you cannot expect addons to update properly in general without restarting the client.
