### ISSUE TITLE
[suggestion] LazyPig shortcut Alt + Ctrl to send mail

### ISSUE THREAD

**Issue by theoden-dd** [shirsig/postal#20]
One more issue regarding [LP](https://github.com/satan666/_LP) in addition to #15.

Mail should be sent by pressing Alt + Ctrl, see their readme:
> send mail(if item is attached to the mail)

Please, consider making it working, if that's not too hard.
If sending mail without attaches start to work too, I don't mind. :)

**Comment by shirsig** [comment]
That's never gonna be compatible. Postal attachments are not the same as the regular attachment (which is built into the api). They're something more abstract only postal knows about. I don't think the shortcut is useful enough to implement it independently.
