### ISSUE TITLE
[suggestion] "Mark all read" button

### ISSUE THREAD

**Issue by theoden-dd** [shirsig/postal#21]
I'll describe my use case to show worth.

I almost never use "Open mail" button, since I use my mailbox as an extension of my bank and inventory. 30 copper for 60 days per item is very good rent price.

However I want to benefit from "New mail" icon near the minimap. To do that I *have to left-click every item I decided to keep in the inbox*.

That's why I'm asking for another button. Thanks for your attention.

If anyone knows another addon having this feature, please advice it.
I could move to that in order not to bother Simon.

**Comment by shirsig** [comment]
But reading reduces the time to like 3 days or something? Also, with the current gold spam mail, the new mail icon hasn't had any benefits in a while.

**Comment by theoden-dd** [comment]
> But reading reduces the time to like 3 days or something?
Didn't know that, actually. I saw this, but though it was a bug, since e.g. on Elysium read mail receives its usual returning time-out after you reopen the in-box.

> Also, with the current gold spam mail, the new mail icon hasn't had any benefits in a while.
That's kind of subjective experience. I've got not so much spam mail. =)

**Comment by shirsig** [comment]
I'm closing this as without the bug the feature seems pointless. There's also the additional issue of the client bug with the mail icon when automatically opening the last mail.
