### ISSUE TITLE
BeanCounter breaks Postal (opening auction house/npc mail will destroy the attachment)

### ISSUE THREAD

**Issue by phorbeus** [shirsig/postal#22]
Hi there, since version https://github.com/shirsig/postal/commit/b3da5338761f9c19900fd6172e688800b7c5de45#diff-488427b9c215e3ca595810fb1905d189R190 of postal does not seem to check if mail (in my case it was mail returned from the auction house) still contains an item before deleting it. Right clicking to open the mail today resulted in me losing a couple a of relatively cheap idols I was trying to sell earlier. Just wanted to let you know before anyone accidentally deletes something more pricey. Otherwise great addon, keep up the good work, it's much appreciated.

**Comment by shirsig** [comment]
Are you certain? I've tested this a lot. What server is it?

**Comment by phorbeus** [comment]
I'm on Nefarian (classic-wow.org). I opened the mailbox, saw the idols returned by the auction house, right clicked all of them but they didn't appear in my inventory. Instead they just vanished. If you like I can try this again later with some really cheap trash items. Will take some time some for the auction to finish though.

**Comment by shirsig** [comment]
Sure they didn't stack or something? I tested it on both elysium and kronos both before uploading and now again and I cannot reproduce it. Not sure if the server could make a difference here.

**Comment by phorbeus** [comment]
Nope, I have no idols in the inventory at all. Testing now to confirm... done.

Right clicking inbox items sent by another character highlights them for a second, but doesn't open/loot the mail.
Right clicking items returned by the auction house instantly destroys them.

**Comment by shirsig** [comment]
sure you have a clean install of the newest version? tried disabling all other addons?

**Comment by phorbeus** [comment]
Testing now with all other addons and Saved Variables removed...

So far it seems to loot items sent by other characters, but sometimes it takes multiple clicks before it opens the mail. Waiting to confirm items returned by auctions.

**Comment by shirsig** [comment]
It's supposed to be one click each for gold, item and text (only if available respectively)

**Comment by phorbeus** [comment]
I did some more testing and the bug seems to be caused by the BeanCounter addon, which is part of the auctioneer package. With BeanCounter disabled I didn't encounter the bug so far.

**Comment by theoden-dd** [comment]
Confirm the bug on Elysium.
My Twisted Chanter's Staff went Twisted Nether when I right-clicked on it after expiring from the AH.

Previously postal worked perfectly, but just today I tired to write down successful sells manually
and recalled that [there'll be no beancounter in aux](https://github.com/shirsig/aux-addon/issues/44).
So I installed [Auctioneer Pack](http://auctioneeraddon.com/dl/zzOld/AuctioneerComplete/auctioneerpack-3.9.0.1000.zip) as Simon recommended in the issue.
It contained beancounter, just as planned...
The rest of the story you know already.

If fixing the bug would be too tedious, I think it deserves at least **big red letters** in the readme.

**Comment by shirsig** [comment]
It's not really a bug, just beancounter doing very bad things. Anyway, I've added makeshift fix that should prevent the deleting, and possibly other conflicts, though of course there is no solution to this kind of problem in general as other addons loaded earlier could always potentially modify api functions in arbitrary ways.

Could you confirm that it works, please? I don't have beancounter.

**Comment by theoden-dd** [comment]
In several minutes. While I'm checking it, quick question: @shirsig what tool do you use to track down your best sells? I wonder what it could be if not beancounter.

**Comment by theoden-dd** [comment]
Successfully collected items and money by right-clicking after beancounter was loaded.

However, still interested in your weapon choice. =)

**Comment by shirsig** [comment]
I get gold by farming mara/dm east
