### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by 0vertime** [shirsig/postal#24]
Error:  attempt to index global `postalHorizontalBarLeft' (a nil value)
File: Interface\AddOns\Postal\postal.lua
Line: 288
Count: 10
--------------------------------------------------
Error:  attempt to index global `postalMailButton' (a nil value)
File: Interface\AddOns\Postal\postal.lua
Line: 527
Count: 5
--------------------------------------------------
Error:  attempt to index global `postalMailButton' (a nil value)
File: Interface\AddOns\Postal\postal.lua
Line: 625
Count: 4

**Comment by shirsig** [comment]
maybe a conflict with moveanything or you didn't update properly (windows case insensitivity issue)

**Comment by 0vertime** [comment]
Seems that the issue was caused by pulling from git with TortoiseGit.

**Comment by shirsig** [comment]
guess that would happen with git in general. I don't think it updates case-changes in file names on windows.
