### ISSUE TITLE
C.O.D payments for multiple items

### ISSUE THREAD

**Issue by Seagulls** [shirsig/postal#25]
If you send multiple items with C.O.D only the first item will have the C.O.D request attached.

It should split the amount you have specified over all items.

Example if you are sending two items and input 10g for C.O.D each item should have 5g C.O.D

**Comment by shirsig** [comment]
Not really. Ideally C.O.D would include all items, like on retail, but that's not possible with the vanilla API.

Only applying it to the first item is somewhat unintuitive but also simple, safe and easy to use once you know this rule.

Splitting the C.O.D. equally would often be wrong (items with different values) and still doesn't allow you to bind items together so either all or none have to be bought, but makes it less obvious that it doesn't.
