### ISSUE TITLE
Errors with the newest update, doesn't work

### ISSUE THREAD

**Issue by GaborSuranyi** [shirsig/postal#26]
After pulling f22e20, postal doesn't work at all.
Tested on a clean wow installation, same effect.

Error logs include:
postal.lua:288
"Attempt to index global `postalHorizontalBarLeft` (a nil value)"
postal.lua:625
samething as above / "postMailButton"

Tried reverting to earlier versions, and deleting WTF, but the error consisted. Maybe there's something else behind these errors? Maybe it's server specific? @Elysium

If you could take a look to figure out what could be causing these issues, I would really appreciate it.

Cheers!

**Comment by shirsig** [comment]
if you're using windows pull isn't going to correctly update case changes in file names

**Comment by GaborSuranyi** [comment]
Yep, that was it. (probably, I can see that even the project name has changed from Postal to postal?)
Thanks for the tip!
