### ISSUE TITLE
Error messages when opening or closing mailbox

### ISSUE THREAD

**Issue by Ghamarro** [shirsig/postal#27]
I get an error message everytime I try to open or close the mailbox. Here's a screenshot of the messages from my Improved Error Frame addon; 
![postal_errors](https://cloud.githubusercontent.com/assets/19500332/26757009/36df687e-48b8-11e7-8501-0d108e503536.jpg)

**Comment by shirsig** [comment]
https://github.com/shirsig/postal/issues/26
