### ISSUE TITLE
incoming mail icon maney

### ISSUE THREAD

**Issue by Monteo** [shirsig/Postal#4]
problems with the incoming e-mail icon with the money from the auction
![wowscrnshot_122216_230155](https://cloud.githubusercontent.com/assets/24656088/21435414/54808ef8-c8ac-11e6-930a-63352f7c55bf.jpg)

**Comment by shirsig** [comment]
doubt this is because of postal, never seen it before

**Comment by fgsfdss** [comment]
This is an Elysium server-side issue.

**Comment by shirsig** [comment]
thanks, I'll close this then.
