### ISSUE TITLE
Left Click add attachment?

### ISSUE THREAD

**Issue by Jakobud** [shirsig/Postal#5]
I'm a little confused by your instructions. You say you can just add an item to the attachments by left clicking it? Because that picks up the item for me and I have to manually drag it over to the mail frame.

One thing I like about Gmail and CT_MailMod is that you can ALT+LeftClick an item in your bag and it automatically adds it to the Mass Mail tab. You should add some sort of functionality that is similar so you can quickly just ALT+Click a bunch of items quickly in stead of manually moving them to the mail frame one after another.

**Comment by shirsig** [comment]
Sorry, it's right-click. Fixed it in the readme.

**Comment by Jakobud** [comment]
Ah thank you
