### ISSUE TITLE
How can I delete names in the 'To: ' list

### ISSUE THREAD

**Issue by hbltth** [shirsig/Postal#53]
Hi thanks for the work.
I want to delete some names in the 'To: ' list, is it possible?

**Comment by shirsig** [comment]
I assume you're talking about the suggestions list? It is populated from 3 sources: the friends list, the guild, and a recent contacts list that Mail itself keeps. The entries from the recent list should be automatically deleted after 30 days, but if you really need to delete them earlier you could directly delete them from the savedvariables file.

**Comment by hbltth** [comment]
Thanks for your answer!
And I think it's maybe better if there is a choice to add names manual, such as adding an 'add' button beside 'To: ' frame. 
Then don't need to pay much attention to choose the correct name, in case of sending to wrong people :).

**Comment by hbltth** [comment]
> I assume you're talking about the suggestions list? It is populated from 3 sources: the friends list, the guild, and a recent contacts list that Mail itself keeps. The entries from the recent list should be automatically deleted after 30 days, but if you really need to delete them earlier you could directly delete them from the savedvariables file.

Thanks for your answer!
And I think it's maybe better if there is a choice to add names manual, such as adding an 'add' button beside 'To: ' frame.
Then don't need to pay much attention to choose the correct name, in case of sending to wrong person :).
