### ISSUE TITLE
Problem after gquit

### ISSUE THREAD

**Issue by sipertruk** [shirsig/Postal#8]
Immediately after gquit i had this:
![postal](https://cloud.githubusercontent.com/assets/7644041/22043511/309fa1f4-dd10-11e6-9755-e23949f070a6.jpg)
Probably related to notes here http://wowwiki.wikia.com/wiki/API_GetNumGuildMembers?oldid=378613

**Comment by shirsig** [comment]
thanks, fixed it.

**Comment by sipertruk** [comment]
At line 824 ignore[name] will still produce a nil index error.

**Comment by shirsig** [comment]
oops, thanks, fixed now

**Comment by sipertruk** [comment]
Working now, thanks.
It also works around ghosts in contact list, elysium bug.
