### ISSUE TITLE
Send mail to bug

### ISSUE THREAD

**Issue by Maroej** [shirsig/Postal#9]
Error occurs when typing in a name that is not suggested by postal.

For example

I start to write a name with starting with S , postal suggests Sweetdeal but I finish it as Scar and it pops up this error
https://s24.postimg.org/reteuw4k5/postal_error.png

**Comment by shirsig** [comment]
Probably was this https://github.com/shirsig/Postal/issues/8 which should be fixed already in the newest version (either because of gquit or the nost bug of having a bad friendlist entry)
